version: '3'
tasks:
  local-build:
    desc: Build the local python environment
    cmds:
      - pip install -r requirements.txt
  build:
    desc: Build the langchain container
    cmds:
      - docker-compose build
  up:
    desc: Start the langchain container
    cmds:
      - docker-compose up
  down:
    desc: Stop the langchain container
    cmds:
      - docker-compose down
